import type { courses } from "@lms-repo/db/schema/service";

type Courses = typeof courses.$inferInsert;
type Optional = "id" | "departmentId" | "professorId";

export const courseList: Omit<Courses, Optional>[] = [
	{
		name: "マクロ経済学",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 1,
		credits: 2,
		requirements: "必修",
		classRoom: "L110",
	},
	{
		name: "ミクロ経済学",
		targetGrade: 1,
		weekdays: "金曜日",
		period: 1,
		credits: 2,
		requirements: "必修",
		classRoom: "L113",
	},
	{
		name: "統計学",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 1,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L115",
	},
	{
		name: "計量経済学",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L113",
	},
	{
		name: "経営学総論",
		targetGrade: 1,
		weekdays: "金曜日",
		period: 1,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L112",
	},
	{
		name: "産業組織論",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L117",
	},
	{
		name: "簿記論",
		targetGrade: 1,
		weekdays: "木曜日",
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L211",
	},
	{
		name: "政治経済学",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L213",
	},
	{
		name: "民法",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L216",
	},
	{
		name: "英語ⅰ",
		targetGrade: 1,
		weekdays: "金曜日",
		period: 4,
		credits: 1,
		requirements: "必修",
		classRoom: "L113",
	},
	{
		name: "ドイツ語",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 2,
		credits: 1,
		requirements: "必修",
		classRoom: "L114",
	},
	{
		name: "フランス語",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 3,
		credits: 1,
		requirements: "必修",
		classRoom: "L114",
	},
	{
		name: "イスラーム史",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L107",
	},
	{
		name: "西洋史",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L107",
	},
	{
		name: "日本史",
		targetGrade: 1,
		weekdays: "木曜日",
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L106",
	},
	{
		name: "経済学史",
		targetGrade: 2,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L106",
	},
	{
		name: "会計学ⅰ",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L206",
	},
	{
		name: "生態学ⅰ",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L103",
	},
	{
		name: "食品科学",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L207",
	},
	{
		name: "環境学",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 5,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L103",
	},
	{
		name: "情報科学",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 1,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L103",
	},
	{
		name: "線形代数学",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "必修",
		classRoom: "L201",
	},
	{
		name: "微分積分学",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 2,
		credits: 2,
		requirements: "必修",
		classRoom: "L202",
	},
	{
		name: "確率論",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L203",
	},
	{
		name: "数理統計学",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L204",
	},
	{
		name: "物理学基礎",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "必修",
		classRoom: "L301",
	},
	{
		name: "化学基礎",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 3,
		credits: 2,
		requirements: "必修",
		classRoom: "L302",
	},
	{
		name: "生物学基礎",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "必修",
		classRoom: "L303",
	},
	{
		name: "地学基礎",
		targetGrade: 1,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "必修",
		classRoom: "L304",
	},
	{
		name: "哲学概論",
		targetGrade: 1,
		weekdays: "金曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L401",
	},
	{
		name: "論理学",
		targetGrade: 2,
		weekdays: "月曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L402",
	},
	{
		name: "倫理学",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L403",
	},
	{
		name: "心理学概論",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L404",
	},
	{
		name: "社会学概論",
		targetGrade: 1,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L405",
	},
	{
		name: "人類学概論",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L406",
	},
	{
		name: "地理学概論",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L407",
	},
	{
		name: "言語学概論",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L408",
	},
	{
		name: "中国語Ⅰ",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L501",
	},
	{
		name: "韓国語Ⅰ",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L502",
	},
	{
		name: "スペイン語Ⅰ",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L503",
	},
	{
		name: "ロシア語Ⅰ",
		targetGrade: 1,
		weekdays: "木曜日",
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L504",
	},
	{
		name: "イタリア語Ⅰ",
		targetGrade: 1,
		weekdays: "金曜日",
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L505",
	},
	{
		name: "ポルトガル語Ⅰ",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L506",
	},
	{
		name: "アラビア語Ⅰ",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 4,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L507",
	},
	{
		name: "ヒンディー語Ⅰ",
		targetGrade: 1,
		weekdays: "水曜日",
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L508",
	},
	{
		name: "ラテン語Ⅰ",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L509",
	},
	{
		name: "古典ギリシャ語Ⅰ",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L510",
	},
	{
		name: "美術史概論",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L601",
	},
	{
		name: "音楽史概論",
		targetGrade: 1,
		weekdays: "火曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L602",
	},
	{
		name: "演劇概論",
		targetGrade: 2,
		weekdays: "水曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L603",
	},
	{
		name: "映画史概論",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L604",
	},
	{
		name: "文学理論",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L605",
	},
	{
		name: "比較文学",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L606",
	},
	{
		name: "日本文学史",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L607",
	},
	{
		name: "中国文学史",
		targetGrade: 2,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L608",
	},
	{
		name: "英米文学史",
		targetGrade: 2,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L609",
	},
	{
		name: "ドイツ文学史",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L610",
	},
	{
		name: "フランス文学史",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L611",
	},
	{
		name: "ロシア文学史",
		targetGrade: 3,
		weekdays: "火曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L612",
	},
	{
		name: "古典文学講読",
		targetGrade: 3,
		weekdays: "水曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L613",
	},
	{
		name: "現代文学講読",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L614",
	},
	{
		name: "詩歌論",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L615",
	},
	{
		name: "小説論",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L616",
	},
	{
		name: "戯曲論",
		targetGrade: 3,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L617",
	},
	{
		name: "評論論",
		targetGrade: 3,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L618",
	},
	{
		name: "創作演習",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L619",
	},
	{
		name: "編集演習",
		targetGrade: 4,
		weekdays: "金曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L620",
	},
	{
		name: "出版論",
		targetGrade: 4,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L621",
	},
	{
		name: "メディア論",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L622",
	},
	{
		name: "ジャーナリズム論",
		targetGrade: 2,
		weekdays: "水曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L623",
	},
	{
		name: "広告論",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L624",
	},
	{
		name: "国際関係論",
		targetGrade: 2,
		weekdays: "金曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L625",
	},
	{
		name: "政治学概論",
		targetGrade: 1,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L626",
	},
	{
		name: "行政学",
		targetGrade: 3,
		weekdays: "火曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L627",
	},
	{
		name: "国際法",
		targetGrade: 3,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L628",
	},
	{
		name: "国際政治",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L629",
	},
	{
		name: "地域研究",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L630",
	},
	{
		name: "文化人類学",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L631",
	},
	{
		name: "社会心理学",
		targetGrade: 3,
		weekdays: "火曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L632",
	},
	{
		name: "発達心理学",
		targetGrade: 2,
		weekdays: "水曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L633",
	},
	{
		name: "臨床心理学",
		targetGrade: 4,
		weekdays: "木曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L634",
	},
	{
		name: "教育心理学",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L635",
	},
	{
		name: "認知心理学",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L636",
	},
	{
		name: "学習心理学",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L637",
	},
	{
		name: "人格心理学",
		targetGrade: 3,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L638",
	},
	{
		name: "集団心理学",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L639",
	},
	{
		name: "健康心理学",
		targetGrade: 4,
		weekdays: "金曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L640",
	},
	{
		name: "産業心理学",
		targetGrade: 4,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L641",
	},
	{
		name: "犯罪心理学",
		targetGrade: 4,
		weekdays: "火曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L642",
	},
	{
		name: "司法心理学",
		targetGrade: 4,
		weekdays: "水曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L643",
	},
	{
		name: "スポーツ心理学",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L644",
	},
	{
		name: "音楽心理学",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L645",
	},
	{
		name: "美術心理学",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L646",
	},
	{
		name: "色彩心理学",
		targetGrade: 2,
		weekdays: "火曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L647",
	},
	{
		name: "環境心理学",
		targetGrade: 3,
		weekdays: "水曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L648",
	},
	{
		name: "交通心理学",
		targetGrade: 4,
		weekdays: "木曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L649",
	},
	{
		name: "消費者心理学",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L650",
	},
	{
		name: "広告心理学",
		targetGrade: 4,
		weekdays: "月曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L651",
	},
	{
		name: "マーケティング心理学",
		targetGrade: 4,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L652",
	},
	{
		name: "コミュニケーション心理学",
		targetGrade: 3,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L653",
	},
	{
		name: "異文化心理学",
		targetGrade: 4,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L654",
	},
	{
		name: "比較心理学",
		targetGrade: 4,
		weekdays: "金曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L655",
	},
	{
		name: "神経心理学",
		targetGrade: 4,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L656",
	},
	{
		name: "応用心理学",
		targetGrade: 4,
		weekdays: "水曜日",
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L663",
	},
	{
		name: "心理学研究法",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L664",
	},
	{
		name: "心理統計学",
		targetGrade: 3,
		weekdays: "金曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L665",
	},
	{
		name: "心理測定法",
		targetGrade: 3,
		weekdays: "月曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L666",
	},
	{
		name: "心理実験法",
		targetGrade: 3,
		weekdays: "火曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L667",
	},
	{
		name: "質的研究法",
		targetGrade: 4,
		weekdays: "水曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L668",
	},
	{
		name: "量的研究法",
		targetGrade: 4,
		weekdays: "木曜日",
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L669",
	},
	{
		name: "混合研究法",
		targetGrade: 4,
		weekdays: "金曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L670",
	},
	{
		name: "縦断研究法",
		targetGrade: 4,
		weekdays: "月曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L671",
	},
	{
		name: "横断研究法",
		targetGrade: 4,
		weekdays: "火曜日",
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L672",
	},
	{
		name: "事例研究法",
		targetGrade: 4,
		weekdays: "水曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L673",
	},
	{
		name: "調査研究法",
		targetGrade: 3,
		weekdays: "木曜日",
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L674",
	},
];
