import type { courses } from "@lms-repo/db/schema/service";

type Courses = typeof courses.$inferInsert;
type Optional = "id" | "departmentId" | "professorId";

// 社会科学共通講義
export const socialScienceCommonCourses: Omit<Courses, Optional>[] = [
	{
		name: "基礎ゼミ",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 2,
		requirements: "必修",
		classRoom: "L101"
	},
	{
		name: "演習ⅰ",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "必修",
		classRoom: "L201"
	},
	{
		name: "演習ⅱ",
		targetGrade: 4,
		weekdays: 3,
		period: 3,
		credits: 1,
		requirements: "必修",
		classRoom: "L301"
	},
	{
		name: "卒業論文",
		targetGrade: 4,
		weekdays: 4,
		period: 4,
		credits: 4,
		requirements: "必修",
		classRoom: "L401"
	},
];

// 自然科学共通講義
export const naturalScienceCommonCourses: Omit<Courses, Optional>[] = [
	{
		name: "基礎演習",
		targetGrade: 2,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "必修",
		classRoom: "L102"
	},
	{
		name: "学生実験・演習ⅰ",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 2,
		requirements: "必修",
		classRoom: "L202"
	},
	{
		name: "学生実験・演習ⅱ",
		targetGrade: 4,
		weekdays: 4,
		period: 4,
		credits: 2,
		requirements: "必修",
		classRoom: "L302"
	},
	{
		name: "卒業研究",
		targetGrade: 4,
		weekdays: 5,
		period: 5,
		credits: 4,
		requirements: "必修",
		classRoom: "L402"
	},
];

// Total courses: 380
export const courseList: Omit<Courses, Optional>[] = [
	{
		name: "イスラーム史",
		targetGrade: 1,
		weekdays: 4,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L106",
	},
	{
		name: "西洋史",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L310",
	},
	{
		name: "日本史",
		targetGrade: 3,
		weekdays: 1,
		period: 1,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L423",
	},
	{
		name: "東洋史",
		targetGrade: 1,
		weekdays: 4,
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L107",
	},
	{
		name: "古代史",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L337",
	},
	{
		name: "中世史",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L150",
	},
	{
		name: "近代史",
		targetGrade: 1,
		weekdays: 2,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L227",
	},
	{
		name: "現代史",
		targetGrade: 1,
		weekdays: 2,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L413",
	},
	{
		name: "社会経済史",
		targetGrade: 2,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L444",
	},
	{
		name: "文化史",
		targetGrade: 1,
		weekdays: 3,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L334",
	},
	{
		name: "思想史",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L422",
	},
	{
		name: "宗教史",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L228",
	},
	{
		name: "美術史",
		targetGrade: 3,
		weekdays: 1,
		period: 1,
		credits: 3,
		requirements: "必修",
		classRoom: "L313",
	},
	{
		name: "音楽史",
		targetGrade: 2,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L236",
	},
	{
		name: "史学概論",
		targetGrade: 2,
		weekdays: 2,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L344",
	},
	{
		name: "西洋哲学史",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L504",
	},
	{
		name: "東洋哲学史",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L139",
	},
	{
		name: "日本文学史",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L140",
	},
	{
		name: "中国文学史",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L102",
	},
	{
		name: "英米文学史",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L137",
	},
	{
		name: "ドイツ文学史",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L304",
	},
	{
		name: "フランス文学史",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L548",
	},
	{
		name: "ロシア文学史",
		targetGrade: 3,
		weekdays: 2,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L221",
	},
	{
		name: "経済学史",
		targetGrade: 1,
		weekdays: 4,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L230",
	},
	{
		name: "法制史",
		targetGrade: 2,
		weekdays: 3,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L116",
	},
	{
		name: "政治思想史",
		targetGrade: 1,
		weekdays: 1,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L213",
	},
	{
		name: "教育史",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L526",
	},
	{
		name: "建築史",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L507",
	},
	{
		name: "哲学概論",
		targetGrade: 3,
		weekdays: 5,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L103",
	},
	{
		name: "論理学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L312",
	},
	{
		name: "近代哲学",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L335",
	},
	{
		name: "現代哲学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L303",
	},
	{
		name: "存在論",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 3,
		requirements: "必修",
		classRoom: "L247",
	},
	{
		name: "認識論",
		targetGrade: 2,
		weekdays: 2,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L446",
	},
	{
		name: "言語哲学",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L515",
	},
	{
		name: "社会哲学",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L327",
	},
	{
		name: "心理学概論",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L323",
	},
	{
		name: "文学理論",
		targetGrade: 1,
		weekdays: 3,
		period: 2,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L146",
	},
	{
		name: "詩歌論",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L533",
	},
	{
		name: "小説論",
		targetGrade: 3,
		weekdays: 1,
		period: 1,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L240",
	},
	{
		name: "戯曲論",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L414",
	},
	{
		name: "評論論",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L411",
	},
	{
		name: "出版論",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L303",
	},
	{
		name: "メディア論",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L414",
	},
	{
		name: "ジャーナリズム論",
		targetGrade: 2,
		weekdays: 3,
		period: 5,
		credits: 1,
		requirements: "必修",
		classRoom: "L144",
	},
	{
		name: "広告論",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L440",
	},
	{
		name: "産業組織論",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L421",
	},
	{
		name: "国際金融論",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L201",
	},
	{
		name: "金融論",
		targetGrade: 2,
		weekdays: 1,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L312",
	},
	{
		name: "経営学総論",
		targetGrade: 2,
		weekdays: 3,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L421",
	},
	{
		name: "経営組織論",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L322",
	},
	{
		name: "経営情報論",
		targetGrade: 3,
		weekdays: 4,
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L111",
	},
	{
		name: "企業論",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L525",
	},
	{
		name: "マーケティング論",
		targetGrade: 2,
		weekdays: 4,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L344",
	},
	{
		name: "財務管理論",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L532",
	},
	{
		name: "中小企業論",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L521",
	},
	{
		name: "戦略管理論",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L240",
	},
	{
		name: "地方公企業論",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L112",
	},
	{
		name: "人的資源管理論ⅰ",
		targetGrade: 3,
		weekdays: 1,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L338",
	},
	{
		name: "人的資源管理論ⅱ",
		targetGrade: 3,
		weekdays: 4,
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L305",
	},
	{
		name: "法哲学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L310",
	},
	{
		name: "政治学概論",
		targetGrade: 1,
		weekdays: 3,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L241",
	},
	{
		name: "国際関係論",
		targetGrade: 1,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L225",
	},
	{
		name: "政治過程論",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L237",
	},
	{
		name: "公共政策論",
		targetGrade: 1,
		weekdays: 2,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L417",
	},
	{
		name: "地方自治論",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L520",
	},
	{
		name: "国際機構論",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L247",
	},
	{
		name: "安全保障論",
		targetGrade: 2,
		weekdays: 4,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L213",
	},
	{
		name: "教育学概論",
		targetGrade: 1,
		weekdays: 5,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L201",
	},
	{
		name: "教育哲学",
		targetGrade: 2,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L129",
	},
	{
		name: "教育課程論",
		targetGrade: 2,
		weekdays: 4,
		period: 5,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L531",
	},
	{
		name: "教育評価論",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L428",
	},
	{
		name: "教育財政論",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L109",
	},
	{
		name: "生涯学習論",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 2,
		requirements: "必修",
		classRoom: "L423",
	},
	{
		name: "高等教育論",
		targetGrade: 2,
		weekdays: 1,
		period: 3,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L125",
	},
	{
		name: "社会学概論",
		targetGrade: 2,
		weekdays: 4,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L512",
	},
	{
		name: "人類学概論",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 1,
		requirements: "必修",
		classRoom: "L501",
	},
	{
		name: "社会政策論",
		targetGrade: 2,
		weekdays: 2,
		period: 1,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L439",
	},
	{
		name: "確率論",
		targetGrade: 1,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "必修",
		classRoom: "L510",
	},
	{
		name: "相対性理論",
		targetGrade: 1,
		weekdays: 2,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L536",
	},
	{
		name: "プログラミング言語論",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L429",
	},
	{
		name: "計算機構成論",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L518",
	},
	{
		name: "データベース論",
		targetGrade: 3,
		weekdays: 4,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L334",
	},
	{
		name: "理論計算機科学",
		targetGrade: 1,
		weekdays: 2,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L523",
	},
	{
		name: "機械工学概論",
		targetGrade: 2,
		weekdays: 1,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L109",
	},
	{
		name: "電気回路理論",
		targetGrade: 3,
		weekdays: 4,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L341",
	},
	{
		name: "建築学概論",
		targetGrade: 2,
		weekdays: 3,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L531",
	},
	{
		name: "循環型社会論",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L517",
	},
	{
		name: "持続可能開発論",
		targetGrade: 2,
		weekdays: 4,
		period: 3,
		credits: 3,
		requirements: "必修",
		classRoom: "L138",
	},
	{
		name: "森林科学概論",
		targetGrade: 1,
		weekdays: 4,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L533",
	},
	{
		name: "在宅看護論",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L343",
	},
	{
		name: "健康管理論",
		targetGrade: 3,
		weekdays: 2,
		period: 5,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L346",
	},
	{
		name: "保健福祉論",
		targetGrade: 3,
		weekdays: 1,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L225",
	},
	{
		name: "倫理学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L301",
	},
	{
		name: "形而上学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L238",
	},
	{
		name: "美学",
		targetGrade: 1,
		weekdays: 4,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L329",
	},
	{
		name: "宗教学",
		targetGrade: 2,
		weekdays: 5,
		period: 1,
		credits: 1,
		requirements: "必修",
		classRoom: "L534",
	},
	{
		name: "統計学",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L115",
	},
	{
		name: "財政学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "必修",
		classRoom: "L114",
	},
	{
		name: "会計学ⅰ",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L303",
	},
	{
		name: "会計学ⅱ",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L234",
	},
	{
		name: "行政学",
		targetGrade: 3,
		weekdays: 2,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L239",
	},
	{
		name: "選挙研究",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L202",
	},
	{
		name: "文化人類学",
		targetGrade: 1,
		weekdays: 1,
		period: 5,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L237",
	},
	{
		name: "微分積分学",
		targetGrade: 2,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L437",
	},
	{
		name: "微分方程式",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L313",
	},
	{
		name: "電磁気学",
		targetGrade: 2,
		weekdays: 2,
		period: 3,
		credits: 2,
		requirements: "必修",
		classRoom: "L340",
	},
	{
		name: "光学",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L429",
	},
	{
		name: "音響学",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L128",
	},
	{
		name: "生態学",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L214",
	},
	{
		name: "火山学",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L141",
	},
	{
		name: "オペレーティングシステム",
		targetGrade: 3,
		weekdays: 1,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L441",
	},
	{
		name: "ソフトウェア工学",
		targetGrade: 2,
		weekdays: 4,
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L112",
	},
	{
		name: "人工知能",
		targetGrade: 3,
		weekdays: 5,
		period: 2,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L146",
	},
	{
		name: "ヒューマンインターフェース",
		targetGrade: 2,
		weekdays: 3,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L315",
	},
	{
		name: "分散システム",
		targetGrade: 2,
		weekdays: 1,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L103",
	},
	{
		name: "生産加工学",
		targetGrade: 2,
		weekdays: 5,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L221",
	},
	{
		name: "熱機関工学",
		targetGrade: 1,
		weekdays: 3,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L516",
	},
	{
		name: "ロボット工学",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L417",
	},
	{
		name: "CAD/CAM",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L536",
	},
	{
		name: "精密加工学",
		targetGrade: 2,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L324",
	},
	{
		name: "メカトロニクス",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L338",
	},
	{
		name: "エネルギー変換工学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L340",
	},
	{
		name: "通信工学",
		targetGrade: 2,
		weekdays: 3,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L531",
	},
	{
		name: "高電圧工学",
		targetGrade: 3,
		weekdays: 5,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L413",
	},
	{
		name: "ディジタル回路",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L136",
	},
	{
		name: "信号処理",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 2,
		requirements: "必修",
		classRoom: "L449",
	},
	{
		name: "電波工学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L422",
	},
	{
		name: "エネルギー工学",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L323",
	},
	{
		name: "都市計画",
		targetGrade: 1,
		weekdays: 1,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L102",
	},
	{
		name: "発酵工学",
		targetGrade: 2,
		weekdays: 5,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L517",
	},
	{
		name: "バイオマスエネルギー",
		targetGrade: 1,
		weekdays: 5,
		period: 1,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L521",
	},
	{
		name: "再生可能エネルギー",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L321",
	},
	{
		name: "砂防工学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L109",
	},
	{
		name: "造林学",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L207",
	},
	{
		name: "自然公園学",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L449",
	},
	{
		name: "緑化工学",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L133",
	},
	{
		name: "小児科学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L415",
	},
	{
		name: "産科婦人科学",
		targetGrade: 2,
		weekdays: 2,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L320",
	},
	{
		name: "神経科学",
		targetGrade: 1,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L206",
	},
	{
		name: "皮膚科学",
		targetGrade: 3,
		weekdays: 2,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L402",
	},
	{
		name: "泌尿器科学",
		targetGrade: 2,
		weekdays: 3,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L540",
	},
	{
		name: "眼科学",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L203",
	},
	{
		name: "耳鼻咽喉科学",
		targetGrade: 1,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L430",
	},
	{
		name: "放射線科学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 4,
		requirements: "必修",
		classRoom: "L448",
	},
	{
		name: "健康行動科学",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L214",
	},
	{
		name: "発達心理学",
		targetGrade: 3,
		weekdays: 5,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L431",
	},
	{
		name: "臨床心理学",
		targetGrade: 2,
		weekdays: 5,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L123",
	},
	{
		name: "教育心理学",
		targetGrade: 2,
		weekdays: 3,
		period: 1,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L132",
	},
	{
		name: "認知心理学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 1,
		requirements: "必修",
		classRoom: "L325",
	},
	{
		name: "集団心理学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L102",
	},
	{
		name: "犯罪心理学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L408",
	},
	{
		name: "司法心理学",
		targetGrade: 1,
		weekdays: 5,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L413",
	},
	{
		name: "スポーツ心理学",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L210",
	},
	{
		name: "音楽心理学",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 4,
		requirements: "必修",
		classRoom: "L319",
	},
	{
		name: "美術心理学",
		targetGrade: 3,
		weekdays: 4,
		period: 2,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L112",
	},
	{
		name: "色彩心理学",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L322",
	},
	{
		name: "環境心理学",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L340",
	},
	{
		name: "交通心理学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L429",
	},
	{
		name: "消費者心理学",
		targetGrade: 2,
		weekdays: 5,
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L308",
	},
	{
		name: "広告心理学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L543",
	},
	{
		name: "マーケティング心理学",
		targetGrade: 1,
		weekdays: 4,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L511",
	},
	{
		name: "比較心理学",
		targetGrade: 2,
		weekdays: 3,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L413",
	},
	{
		name: "神経心理学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L411",
	},
	{
		name: "応用心理学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L233",
	},
	{
		name: "心理学研究法",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 2,
		requirements: "必修",
		classRoom: "L129",
	},
	{
		name: "心理統計学",
		targetGrade: 1,
		weekdays: 3,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L349",
	},
	{
		name: "心理測定法",
		targetGrade: 1,
		weekdays: 5,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L412",
	},
	{
		name: "心理実験法",
		targetGrade: 3,
		weekdays: 1,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L338",
	},
	{
		name: "社会心理学",
		targetGrade: 1,
		weekdays: 5,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L527",
	},
	{
		name: "人格心理学",
		targetGrade: 2,
		weekdays: 5,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L527",
	},
	{
		name: "産業心理学",
		targetGrade: 1,
		weekdays: 3,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L103",
	},
	{
		name: "コミュニケーション心理学",
		targetGrade: 3,
		weekdays: 4,
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L504",
	},
	{
		name: "異文化心理学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L125",
	},
	{
		name: "生理心理学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L501",
	},
	{
		name: "学習心理学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L313",
	},
	{
		name: "比較文学",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "必修",
		classRoom: "L433",
	},
	{
		name: "古典文学講読",
		targetGrade: 1,
		weekdays: 2,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L333",
	},
	{
		name: "現代文学講読",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L518",
	},
	{
		name: "マクロ経済学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 3,
		requirements: "必修",
		classRoom: "L319",
	},
	{
		name: "ミクロ経済学",
		targetGrade: 3,
		weekdays: 2,
		period: 3,
		credits: 1,
		requirements: "必修",
		classRoom: "L105",
	},
	{
		name: "計量経済学",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L437",
	},
	{
		name: "国際経済学",
		targetGrade: 2,
		weekdays: 1,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L240",
	},
	{
		name: "経済思想",
		targetGrade: 1,
		weekdays: 2,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L412",
	},
	{
		name: "環境経済学",
		targetGrade: 2,
		weekdays: 1,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L416",
	},
	{
		name: "文化経済学",
		targetGrade: 2,
		weekdays: 1,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L235",
	},
	{
		name: "農業経済学",
		targetGrade: 2,
		weekdays: 3,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L516",
	},
	{
		name: "政治経済学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L402",
	},
	{
		name: "教育経営学",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L123",
	},
	{
		name: "森林経営学",
		targetGrade: 2,
		weekdays: 1,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L234",
	},
	{
		name: "民法",
		targetGrade: 2,
		weekdays: 4,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L118",
	},
	{
		name: "刑法",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L345",
	},
	{
		name: "憲法",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L315",
	},
	{
		name: "行政法",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L245",
	},
	{
		name: "商法",
		targetGrade: 3,
		weekdays: 4,
		period: 2,
		credits: 3,
		requirements: "必修",
		classRoom: "L429",
	},
	{
		name: "民事訴訟法",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L409",
	},
	{
		name: "刑事訴訟法",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L205",
	},
	{
		name: "労働法",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L215",
	},
	{
		name: "国際法",
		targetGrade: 1,
		weekdays: 5,
		period: 4,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L419",
	},
	{
		name: "国際私法",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L417",
	},
	{
		name: "法社会学",
		targetGrade: 1,
		weekdays: 4,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L406",
	},
	{
		name: "比較法学",
		targetGrade: 2,
		weekdays: 4,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L238",
	},
	{
		name: "法医学",
		targetGrade: 3,
		weekdays: 1,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L243",
	},
	{
		name: "国際政治",
		targetGrade: 1,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L204",
	},
	{
		name: "比較政治学",
		targetGrade: 2,
		weekdays: 2,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L502",
	},
	{
		name: "政治社会学",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L303",
	},
	{
		name: "教育方法学",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L346",
	},
	{
		name: "社会調査法",
		targetGrade: 3,
		weekdays: 4,
		period: 3,
		credits: 4,
		requirements: "必修",
		classRoom: "L140",
	},
	{
		name: "電気法規",
		targetGrade: 3,
		weekdays: 2,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L134",
	},
	{
		name: "建築法規",
		targetGrade: 1,
		weekdays: 2,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L320",
	},
	{
		name: "看護研究法",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L344",
	},
	{
		name: "地域研究",
		targetGrade: 1,
		weekdays: 4,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L127",
	},
	{
		name: "地学基礎",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L330",
	},
	{
		name: "地質学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L327",
	},
	{
		name: "岩石学",
		targetGrade: 2,
		weekdays: 1,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L230",
	},
	{
		name: "鉱物学",
		targetGrade: 1,
		weekdays: 4,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L525",
	},
	{
		name: "構造地質学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L244",
	},
	{
		name: "地層学",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L111",
	},
	{
		name: "地震学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L448",
	},
	{
		name: "海洋地質学",
		targetGrade: 1,
		weekdays: 5,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L518",
	},
	{
		name: "惑星地質学",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L127",
	},
	{
		name: "環境地質学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L349",
	},
	{
		name: "応用地質学",
		targetGrade: 1,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L246",
	},
	{
		name: "地質工学",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L519",
	},
	{
		name: "地域看護学",
		targetGrade: 1,
		weekdays: 4,
		period: 5,
		credits: 1,
		requirements: "必修",
		classRoom: "L439",
	},
	{
		name: "教育社会学",
		targetGrade: 1,
		weekdays: 1,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L524",
	},
	{
		name: "教育行政学",
		targetGrade: 1,
		weekdays: 4,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L442",
	},
	{
		name: "比較教育学",
		targetGrade: 3,
		weekdays: 2,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L233",
	},
	{
		name: "教育技術学",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L350",
	},
	{
		name: "特別支援教育",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L532",
	},
	{
		name: "健康教育学",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 1,
		requirements: "必修",
		classRoom: "L424",
	},
	{
		name: "社会統計学",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L438",
	},
	{
		name: "家族社会学",
		targetGrade: 3,
		weekdays: 1,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L407",
	},
	{
		name: "都市社会学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L502",
	},
	{
		name: "農村社会学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 4,
		requirements: "必修",
		classRoom: "L244",
	},
	{
		name: "産業社会学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L518",
	},
	{
		name: "医療社会学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L209",
	},
	{
		name: "犯罪社会学",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L522",
	},
	{
		name: "数学基礎",
		targetGrade: 1,
		weekdays: 5,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L302",
	},
	{
		name: "線形代数学",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L207",
	},
	{
		name: "解析学",
		targetGrade: 2,
		weekdays: 4,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L110",
	},
	{
		name: "代数学",
		targetGrade: 3,
		weekdays: 3,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L533",
	},
	{
		name: "幾何学",
		targetGrade: 2,
		weekdays: 5,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L336",
	},
	{
		name: "位相数学",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L518",
	},
	{
		name: "関数解析学",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 3,
		requirements: "必修",
		classRoom: "L544",
	},
	{
		name: "数値解析",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L146",
	},
	{
		name: "離散数学",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L502",
	},
	{
		name: "統計数学",
		targetGrade: 1,
		weekdays: 4,
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L424",
	},
	{
		name: "物理学基礎",
		targetGrade: 1,
		weekdays: 3,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L233",
	},
	{
		name: "力学",
		targetGrade: 1,
		weekdays: 2,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L213",
	},
	{
		name: "熱力学",
		targetGrade: 1,
		weekdays: 4,
		period: 3,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L350",
	},
	{
		name: "統計力学",
		targetGrade: 2,
		weekdays: 2,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L214",
	},
	{
		name: "量子力学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L513",
	},
	{
		name: "原子物理学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L326",
	},
	{
		name: "核物理学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L445",
	},
	{
		name: "素粒子物理学",
		targetGrade: 1,
		weekdays: 3,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L119",
	},
	{
		name: "宇宙物理学",
		targetGrade: 2,
		weekdays: 1,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L332",
	},
	{
		name: "物性物理学",
		targetGrade: 3,
		weekdays: 5,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L231",
	},
	{
		name: "プラズマ物理学",
		targetGrade: 1,
		weekdays: 3,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L233",
	},
	{
		name: "生物物理学",
		targetGrade: 2,
		weekdays: 3,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L148",
	},
	{
		name: "物理化学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L124",
	},
	{
		name: "地球物理学",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L512",
	},
	{
		name: "材料力学",
		targetGrade: 3,
		weekdays: 2,
		period: 3,
		credits: 3,
		requirements: "必修",
		classRoom: "L318",
	},
	{
		name: "流体力学",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L217",
	},
	{
		name: "建築構造力学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L510",
	},
	{
		name: "木材物理学",
		targetGrade: 3,
		weekdays: 5,
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L149",
	},
	{
		name: "化学基礎",
		targetGrade: 3,
		weekdays: 4,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L318",
	},
	{
		name: "無機化学",
		targetGrade: 2,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L213",
	},
	{
		name: "有機化学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L228",
	},
	{
		name: "分析化学",
		targetGrade: 2,
		weekdays: 2,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L213",
	},
	{
		name: "高分子化学",
		targetGrade: 3,
		weekdays: 2,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L545",
	},
	{
		name: "生物化学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L348",
	},
	{
		name: "環境化学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L116",
	},
	{
		name: "材料化学",
		targetGrade: 1,
		weekdays: 1,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L113",
	},
	{
		name: "工業化学",
		targetGrade: 2,
		weekdays: 3,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L109",
	},
	{
		name: "医薬品化学",
		targetGrade: 2,
		weekdays: 1,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L443",
	},
	{
		name: "食品化学",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L514",
	},
	{
		name: "触媒化学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L438",
	},
	{
		name: "錯体化学",
		targetGrade: 2,
		weekdays: 1,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L240",
	},
	{
		name: "放射化学",
		targetGrade: 1,
		weekdays: 3,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L105",
	},
	{
		name: "計算化学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L550",
	},
	{
		name: "進化学",
		targetGrade: 2,
		weekdays: 2,
		period: 4,
		credits: 1,
		requirements: "任意",
		classRoom: "L438",
	},
	{
		name: "地球化学",
		targetGrade: 2,
		weekdays: 5,
		period: 4,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L402",
	},
	{
		name: "森林化学",
		targetGrade: 1,
		weekdays: 5,
		period: 5,
		credits: 4,
		requirements: "必修",
		classRoom: "L206",
	},
	{
		name: "生化学",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L436",
	},
	{
		name: "生物学基礎",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L319",
	},
	{
		name: "細胞生物学",
		targetGrade: 2,
		weekdays: 5,
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L414",
	},
	{
		name: "分子生物学",
		targetGrade: 3,
		weekdays: 1,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L444",
	},
	{
		name: "遺伝学",
		targetGrade: 2,
		weekdays: 1,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L432",
	},
	{
		name: "発生生物学",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L310",
	},
	{
		name: "微生物学",
		targetGrade: 1,
		weekdays: 2,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L549",
	},
	{
		name: "神経生物学",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L140",
	},
	{
		name: "生物統計学",
		targetGrade: 1,
		weekdays: 4,
		period: 2,
		credits: 3,
		requirements: "必修",
		classRoom: "L310",
	},
	{
		name: "古生物学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L210",
	},
	{
		name: "応用微生物学",
		targetGrade: 2,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L443",
	},
	{
		name: "環境微生物学",
		targetGrade: 3,
		weekdays: 1,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L444",
	},
	{
		name: "生物資源利用学",
		targetGrade: 3,
		weekdays: 3,
		period: 2,
		credits: 3,
		requirements: "任意",
		classRoom: "L549",
	},
	{
		name: "植物生理学",
		targetGrade: 2,
		weekdays: 4,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L531",
	},
	{
		name: "動物生理学",
		targetGrade: 3,
		weekdays: 5,
		period: 2,
		credits: 1,
		requirements: "任意",
		classRoom: "L224",
	},
	{
		name: "解剖学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L319",
	},
	{
		name: "生理学",
		targetGrade: 2,
		weekdays: 5,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L435",
	},
	{
		name: "病理学",
		targetGrade: 2,
		weekdays: 2,
		period: 5,
		credits: 3,
		requirements: "任意",
		classRoom: "L523",
	},
	{
		name: "薬理学",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L514",
	},
	{
		name: "内科学",
		targetGrade: 2,
		weekdays: 4,
		period: 1,
		credits: 3,
		requirements: "選択必修",
		classRoom: "L127",
	},
	{
		name: "外科学",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L539",
	},
	{
		name: "精神医学",
		targetGrade: 1,
		weekdays: 1,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L343",
	},
	{
		name: "保健医療行政",
		targetGrade: 2,
		weekdays: 4,
		period: 4,
		credits: 1,
		requirements: "必修",
		classRoom: "L543",
	},
	{
		name: "免疫学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L541",
	},
	{
		name: "公衆衛生学",
		targetGrade: 3,
		weekdays: 4,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L342",
	},
	{
		name: "疫学",
		targetGrade: 3,
		weekdays: 5,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L410",
	},
	{
		name: "保健統計学",
		targetGrade: 3,
		weekdays: 5,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L516",
	},
	{
		name: "精神保健学",
		targetGrade: 3,
		weekdays: 3,
		period: 3,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L424",
	},
	{
		name: "学校保健",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L110",
	},
	{
		name: "産業保健",
		targetGrade: 3,
		weekdays: 1,
		period: 5,
		credits: 4,
		requirements: "必修",
		classRoom: "L206",
	},
	{
		name: "老年保健",
		targetGrade: 1,
		weekdays: 5,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L346",
	},
	{
		name: "母子保健",
		targetGrade: 2,
		weekdays: 4,
		period: 2,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L232",
	},
	{
		name: "国際保健",
		targetGrade: 1,
		weekdays: 5,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L122",
	},
	{
		name: "情報科学基礎",
		targetGrade: 1,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L135",
	},
	{
		name: "アルゴリズムとデータ構造",
		targetGrade: 3,
		weekdays: 5,
		period: 2,
		credits: 4,
		requirements: "必修",
		classRoom: "L447",
	},
	{
		name: "コンピュータネットワーク",
		targetGrade: 1,
		weekdays: 4,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L324",
	},
	{
		name: "コンピュータグラフィックス",
		targetGrade: 1,
		weekdays: 2,
		period: 4,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L434",
	},
	{
		name: "看護情報学",
		targetGrade: 1,
		weekdays: 2,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L518",
	},
	{
		name: "機械学習",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 4,
		requirements: "任意",
		classRoom: "L535",
	},
	{
		name: "機械設計",
		targetGrade: 1,
		weekdays: 2,
		period: 4,
		credits: 4,
		requirements: "必修",
		classRoom: "L414",
	},
	{
		name: "制御工学",
		targetGrade: 2,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L115",
	},
	{
		name: "機械材料学",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 4,
		requirements: "任意",
		classRoom: "L442",
	},
	{
		name: "機械振動学",
		targetGrade: 3,
		weekdays: 2,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L125",
	},
	{
		name: "流体機械",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L547",
	},
	{
		name: "電気材料学",
		targetGrade: 3,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L109",
	},
	{
		name: "建築材料学",
		targetGrade: 2,
		weekdays: 3,
		period: 1,
		credits: 1,
		requirements: "任意",
		classRoom: "L342",
	},
	{
		name: "電子回路",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L347",
	},
	{
		name: "電力システム工学",
		targetGrade: 1,
		weekdays: 4,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L347",
	},
	{
		name: "電気機器",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L250",
	},
	{
		name: "電力電子工学",
		targetGrade: 1,
		weekdays: 2,
		period: 5,
		credits: 2,
		requirements: "必修",
		classRoom: "L215",
	},
	{
		name: "電気計測",
		targetGrade: 1,
		weekdays: 5,
		period: 2,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L429",
	},
	{
		name: "建築設計",
		targetGrade: 2,
		weekdays: 4,
		period: 3,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L318",
	},
	{
		name: "建築環境工学",
		targetGrade: 3,
		weekdays: 4,
		period: 3,
		credits: 3,
		requirements: "必修",
		classRoom: "L247",
	},
	{
		name: "建築設備工学",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L244",
	},
	{
		name: "建築生産",
		targetGrade: 1,
		weekdays: 3,
		period: 4,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L402",
	},
	{
		name: "建築音響",
		targetGrade: 3,
		weekdays: 4,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L417",
	},
	{
		name: "建築照明",
		targetGrade: 3,
		weekdays: 2,
		period: 2,
		credits: 4,
		requirements: "任意",
		classRoom: "L337",
	},
	{
		name: "建築積算",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L517",
	},
	{
		name: "建築施工",
		targetGrade: 1,
		weekdays: 3,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L312",
	},
	{
		name: "建築耐震",
		targetGrade: 1,
		weekdays: 5,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L434",
	},
	{
		name: "建築デザイン",
		targetGrade: 1,
		weekdays: 3,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L244",
	},
	{
		name: "食品科学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L245",
	},
	{
		name: "環境学",
		targetGrade: 2,
		weekdays: 5,
		period: 5,
		credits: 2,
		requirements: "必修",
		classRoom: "L327",
	},
	{
		name: "栄養学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 3,
		requirements: "任意",
		classRoom: "L516",
	},
	{
		name: "食品衛生学",
		targetGrade: 2,
		weekdays: 4,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L529",
	},
	{
		name: "環境生態学",
		targetGrade: 3,
		weekdays: 2,
		period: 4,
		credits: 3,
		requirements: "任意",
		classRoom: "L336",
	},
	{
		name: "環境保全学",
		targetGrade: 3,
		weekdays: 4,
		period: 2,
		credits: 2,
		requirements: "任意",
		classRoom: "L147",
	},
	{
		name: "環境保健学",
		targetGrade: 1,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "選択必修",
		classRoom: "L103",
	},
	{
		name: "林木育種学",
		targetGrade: 3,
		weekdays: 2,
		period: 5,
		credits: 2,
		requirements: "選択必修",
		classRoom: "L531",
	},
	{
		name: "森林生態学",
		targetGrade: 2,
		weekdays: 1,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L146",
	},
	{
		name: "森林土木学",
		targetGrade: 2,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L428",
	},
	{
		name: "林産加工学",
		targetGrade: 3,
		weekdays: 1,
		period: 4,
		credits: 3,
		requirements: "必修",
		classRoom: "L233",
	},
	{
		name: "森林保護学",
		targetGrade: 2,
		weekdays: 3,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L437",
	},
	{
		name: "森林計画学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L320",
	},
	{
		name: "森林利用学",
		targetGrade: 3,
		weekdays: 2,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L320",
	},
	{
		name: "森林政策学",
		targetGrade: 2,
		weekdays: 3,
		period: 5,
		credits: 1,
		requirements: "任意",
		classRoom: "L403",
	},
	{
		name: "基礎看護学",
		targetGrade: 3,
		weekdays: 1,
		period: 3,
		credits: 1,
		requirements: "任意",
		classRoom: "L448",
	},
	{
		name: "成人看護学",
		targetGrade: 3,
		weekdays: 4,
		period: 5,
		credits: 4,
		requirements: "任意",
		classRoom: "L115",
	},
	{
		name: "老年看護学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 2,
		requirements: "任意",
		classRoom: "L147",
	},
	{
		name: "小児看護学",
		targetGrade: 3,
		weekdays: 2,
		period: 1,
		credits: 3,
		requirements: "必修",
		classRoom: "L509",
	},
	{
		name: "母性看護学",
		targetGrade: 3,
		weekdays: 3,
		period: 1,
		credits: 4,
		requirements: "任意",
		classRoom: "L210",
	},
	{
		name: "精神看護学",
		targetGrade: 2,
		weekdays: 5,
		period: 3,
		credits: 3,
		requirements: "任意",
		classRoom: "L319",
	},
	{
		name: "国際看護学",
		targetGrade: 1,
		weekdays: 3,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L211",
	},
	{
		name: "看護管理学",
		targetGrade: 1,
		weekdays: 5,
		period: 5,
		credits: 2,
		requirements: "任意",
		classRoom: "L131",
	},
	{
		name: "看護倫理",
		targetGrade: 1,
		weekdays: 5,
		period: 1,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L217",
	},
	{
		name: "緩和ケア看護",
		targetGrade: 3,
		weekdays: 5,
		period: 3,
		credits: 2,
		requirements: "任意",
		classRoom: "L108",
	},
	{
		name: "リハビリ看護",
		targetGrade: 2,
		weekdays: 5,
		period: 4,
		credits: 2,
		requirements: "任意",
		classRoom: "L235",
	},
	{
		name: "感染症看護",
		targetGrade: 2,
		weekdays: 5,
		period: 5,
		credits: 1,
		requirements: "選択必修",
		classRoom: "L430",
	},
	...socialScienceCommonCourses,
	...naturalScienceCommonCourses,
];
