/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyPageRouteRouteImport } from './routes/_my-page/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyPageProfileRouteImport } from './routes/_my-page/profile'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSetTwofactorRouteImport } from './routes/_auth/set-twofactor'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRequestResetPasswordRouteImport } from './routes/_auth/request-reset-password'
import { Route as AuthAddPasskeyRouteImport } from './routes/_auth/add-passkey'
import { Route as MyPageStudentRouteRouteImport } from './routes/_my-page/_student/route'
import { Route as MyPageProfRouteRouteImport } from './routes/_my-page/_prof/route'
import { Route as MyPageStudentSchedulesRouteImport } from './routes/_my-page/_student/schedules'
import { Route as MyPageStudentRegisterCoursesRouteImport } from './routes/_my-page/_student/register-courses'
import { Route as MyPageStudentNotificationsRouteImport } from './routes/_my-page/_student/notifications'
import { Route as MyPageStudentDashboardRouteImport } from './routes/_my-page/_student/dashboard'
import { Route as MyPageStudentCourseListRouteImport } from './routes/_my-page/_student/course-list'
import { Route as MyPageProfCourseManagementRouteImport } from './routes/_my-page/_prof/course-management'

const MyPageRouteRoute = MyPageRouteRouteImport.update({
  id: '/_my-page',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPageProfileRoute = MyPageProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyPageRouteRoute,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetTwofactorRoute = AuthSetTwofactorRouteImport.update({
  id: '/set-twofactor',
  path: '/set-twofactor',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRequestResetPasswordRoute =
  AuthRequestResetPasswordRouteImport.update({
    id: '/request-reset-password',
    path: '/request-reset-password',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAddPasskeyRoute = AuthAddPasskeyRouteImport.update({
  id: '/add-passkey',
  path: '/add-passkey',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MyPageStudentRouteRoute = MyPageStudentRouteRouteImport.update({
  id: '/_student',
  getParentRoute: () => MyPageRouteRoute,
} as any)
const MyPageProfRouteRoute = MyPageProfRouteRouteImport.update({
  id: '/_prof',
  getParentRoute: () => MyPageRouteRoute,
} as any)
const MyPageStudentSchedulesRoute = MyPageStudentSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => MyPageStudentRouteRoute,
} as any)
const MyPageStudentRegisterCoursesRoute =
  MyPageStudentRegisterCoursesRouteImport.update({
    id: '/register-courses',
    path: '/register-courses',
    getParentRoute: () => MyPageStudentRouteRoute,
  } as any)
const MyPageStudentNotificationsRoute =
  MyPageStudentNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => MyPageStudentRouteRoute,
  } as any)
const MyPageStudentDashboardRoute = MyPageStudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MyPageStudentRouteRoute,
} as any)
const MyPageStudentCourseListRoute = MyPageStudentCourseListRouteImport.update({
  id: '/course-list',
  path: '/course-list',
  getParentRoute: () => MyPageStudentRouteRoute,
} as any)
const MyPageProfCourseManagementRoute =
  MyPageProfCourseManagementRouteImport.update({
    id: '/course-management',
    path: '/course-management',
    getParentRoute: () => MyPageProfRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-passkey': typeof AuthAddPasskeyRoute
  '/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-twofactor': typeof AuthSetTwofactorRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/profile': typeof MyPageProfileRoute
  '/course-management': typeof MyPageProfCourseManagementRoute
  '/course-list': typeof MyPageStudentCourseListRoute
  '/dashboard': typeof MyPageStudentDashboardRoute
  '/notifications': typeof MyPageStudentNotificationsRoute
  '/register-courses': typeof MyPageStudentRegisterCoursesRoute
  '/schedules': typeof MyPageStudentSchedulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-passkey': typeof AuthAddPasskeyRoute
  '/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/set-twofactor': typeof AuthSetTwofactorRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/profile': typeof MyPageProfileRoute
  '/course-management': typeof MyPageProfCourseManagementRoute
  '/course-list': typeof MyPageStudentCourseListRoute
  '/dashboard': typeof MyPageStudentDashboardRoute
  '/notifications': typeof MyPageStudentNotificationsRoute
  '/register-courses': typeof MyPageStudentRegisterCoursesRoute
  '/schedules': typeof MyPageStudentSchedulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_my-page': typeof MyPageRouteRouteWithChildren
  '/_my-page/_prof': typeof MyPageProfRouteRouteWithChildren
  '/_my-page/_student': typeof MyPageStudentRouteRouteWithChildren
  '/_auth/add-passkey': typeof AuthAddPasskeyRoute
  '/_auth/request-reset-password': typeof AuthRequestResetPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/set-twofactor': typeof AuthSetTwofactorRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_my-page/profile': typeof MyPageProfileRoute
  '/_my-page/_prof/course-management': typeof MyPageProfCourseManagementRoute
  '/_my-page/_student/course-list': typeof MyPageStudentCourseListRoute
  '/_my-page/_student/dashboard': typeof MyPageStudentDashboardRoute
  '/_my-page/_student/notifications': typeof MyPageStudentNotificationsRoute
  '/_my-page/_student/register-courses': typeof MyPageStudentRegisterCoursesRoute
  '/_my-page/_student/schedules': typeof MyPageStudentSchedulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-passkey'
    | '/request-reset-password'
    | '/reset-password'
    | '/set-twofactor'
    | '/sign-in'
    | '/sign-up'
    | '/verify-otp'
    | '/profile'
    | '/course-management'
    | '/course-list'
    | '/dashboard'
    | '/notifications'
    | '/register-courses'
    | '/schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-passkey'
    | '/request-reset-password'
    | '/reset-password'
    | '/set-twofactor'
    | '/sign-in'
    | '/sign-up'
    | '/verify-otp'
    | '/profile'
    | '/course-management'
    | '/course-list'
    | '/dashboard'
    | '/notifications'
    | '/register-courses'
    | '/schedules'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_my-page'
    | '/_my-page/_prof'
    | '/_my-page/_student'
    | '/_auth/add-passkey'
    | '/_auth/request-reset-password'
    | '/_auth/reset-password'
    | '/_auth/set-twofactor'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-otp'
    | '/_my-page/profile'
    | '/_my-page/_prof/course-management'
    | '/_my-page/_student/course-list'
    | '/_my-page/_student/dashboard'
    | '/_my-page/_student/notifications'
    | '/_my-page/_student/register-courses'
    | '/_my-page/_student/schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MyPageRouteRoute: typeof MyPageRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_my-page': {
      id: '/_my-page'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MyPageRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_my-page/profile': {
      id: '/_my-page/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MyPageProfileRouteImport
      parentRoute: typeof MyPageRouteRoute
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/set-twofactor': {
      id: '/_auth/set-twofactor'
      path: '/set-twofactor'
      fullPath: '/set-twofactor'
      preLoaderRoute: typeof AuthSetTwofactorRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/request-reset-password': {
      id: '/_auth/request-reset-password'
      path: '/request-reset-password'
      fullPath: '/request-reset-password'
      preLoaderRoute: typeof AuthRequestResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/add-passkey': {
      id: '/_auth/add-passkey'
      path: '/add-passkey'
      fullPath: '/add-passkey'
      preLoaderRoute: typeof AuthAddPasskeyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_my-page/_student': {
      id: '/_my-page/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MyPageStudentRouteRouteImport
      parentRoute: typeof MyPageRouteRoute
    }
    '/_my-page/_prof': {
      id: '/_my-page/_prof'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MyPageProfRouteRouteImport
      parentRoute: typeof MyPageRouteRoute
    }
    '/_my-page/_student/schedules': {
      id: '/_my-page/_student/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof MyPageStudentSchedulesRouteImport
      parentRoute: typeof MyPageStudentRouteRoute
    }
    '/_my-page/_student/register-courses': {
      id: '/_my-page/_student/register-courses'
      path: '/register-courses'
      fullPath: '/register-courses'
      preLoaderRoute: typeof MyPageStudentRegisterCoursesRouteImport
      parentRoute: typeof MyPageStudentRouteRoute
    }
    '/_my-page/_student/notifications': {
      id: '/_my-page/_student/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof MyPageStudentNotificationsRouteImport
      parentRoute: typeof MyPageStudentRouteRoute
    }
    '/_my-page/_student/dashboard': {
      id: '/_my-page/_student/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MyPageStudentDashboardRouteImport
      parentRoute: typeof MyPageStudentRouteRoute
    }
    '/_my-page/_student/course-list': {
      id: '/_my-page/_student/course-list'
      path: '/course-list'
      fullPath: '/course-list'
      preLoaderRoute: typeof MyPageStudentCourseListRouteImport
      parentRoute: typeof MyPageStudentRouteRoute
    }
    '/_my-page/_prof/course-management': {
      id: '/_my-page/_prof/course-management'
      path: '/course-management'
      fullPath: '/course-management'
      preLoaderRoute: typeof MyPageProfCourseManagementRouteImport
      parentRoute: typeof MyPageProfRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAddPasskeyRoute: typeof AuthAddPasskeyRoute
  AuthRequestResetPasswordRoute: typeof AuthRequestResetPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSetTwofactorRoute: typeof AuthSetTwofactorRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAddPasskeyRoute: AuthAddPasskeyRoute,
  AuthRequestResetPasswordRoute: AuthRequestResetPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSetTwofactorRoute: AuthSetTwofactorRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MyPageProfRouteRouteChildren {
  MyPageProfCourseManagementRoute: typeof MyPageProfCourseManagementRoute
}

const MyPageProfRouteRouteChildren: MyPageProfRouteRouteChildren = {
  MyPageProfCourseManagementRoute: MyPageProfCourseManagementRoute,
}

const MyPageProfRouteRouteWithChildren = MyPageProfRouteRoute._addFileChildren(
  MyPageProfRouteRouteChildren,
)

interface MyPageStudentRouteRouteChildren {
  MyPageStudentCourseListRoute: typeof MyPageStudentCourseListRoute
  MyPageStudentDashboardRoute: typeof MyPageStudentDashboardRoute
  MyPageStudentNotificationsRoute: typeof MyPageStudentNotificationsRoute
  MyPageStudentRegisterCoursesRoute: typeof MyPageStudentRegisterCoursesRoute
  MyPageStudentSchedulesRoute: typeof MyPageStudentSchedulesRoute
}

const MyPageStudentRouteRouteChildren: MyPageStudentRouteRouteChildren = {
  MyPageStudentCourseListRoute: MyPageStudentCourseListRoute,
  MyPageStudentDashboardRoute: MyPageStudentDashboardRoute,
  MyPageStudentNotificationsRoute: MyPageStudentNotificationsRoute,
  MyPageStudentRegisterCoursesRoute: MyPageStudentRegisterCoursesRoute,
  MyPageStudentSchedulesRoute: MyPageStudentSchedulesRoute,
}

const MyPageStudentRouteRouteWithChildren =
  MyPageStudentRouteRoute._addFileChildren(MyPageStudentRouteRouteChildren)

interface MyPageRouteRouteChildren {
  MyPageProfRouteRoute: typeof MyPageProfRouteRouteWithChildren
  MyPageStudentRouteRoute: typeof MyPageStudentRouteRouteWithChildren
  MyPageProfileRoute: typeof MyPageProfileRoute
}

const MyPageRouteRouteChildren: MyPageRouteRouteChildren = {
  MyPageProfRouteRoute: MyPageProfRouteRouteWithChildren,
  MyPageStudentRouteRoute: MyPageStudentRouteRouteWithChildren,
  MyPageProfileRoute: MyPageProfileRoute,
}

const MyPageRouteRouteWithChildren = MyPageRouteRoute._addFileChildren(
  MyPageRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MyPageRouteRoute: MyPageRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
