services:
  server:
    container_name: lms-server
    build:
      # ビルド対象をルートディレクトリ（docker-compose.ymlのあるディレクトリから見た場合../）に設定
      context: ..
      # このブロックに限りカレントディレクトリはルートディレクトリを指す
      dockerfile: apps/server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      # ホストのルートディレクトリをコンテナにマウント
      - ..:/lms-repo
      # node_modulesをホストと分離してコンテナにマウント
      - node_modules:/lms-repo/node_modules
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/lmsdb
      NODE_ENV: development
    depends_on:
      - db

  web:
    container_name: lms-web
    build:
      # ビルド対象をルートディレクトリ（docker-compose.ymlのあるディレクトリから見た場合../）に設定
      context: ..
      # このブロックに限りカレントディレクトリはルートディレクトリを指す
      dockerfile: apps/web/Dockerfile
    ports:
      - 3001:3001
    volumes:
      # ホストのルートディレクトリをコンテナにマウント
      - ..:/lms-repo
      # node_modulesをホストと分離してコンテナにマウント
      - node_modules:/lms-repo/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - server

  db:
    container_name: lms-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lmsdb
    ports:
      - 5432:5432
    volumes:
      # PostgreSQLのデータを永続化
      - postgres_data:/var/lib/postgresql

volumes:
  node_modules:
  postgres_data:

